/* eslint-disable sort-keys */
import { darken, lighten, rgba } from 'polished';

const colors = {
  background: '#FFF',
  primary: '#27A8E0',
  secondary: '#626E7A',
  accent: '#CCC',
  white: '#FFF',
  black: '#070707',
  shadow: '#B8B8B8',
  success: '#58966B',
  error: '#C81905',
};

const tokens = {
  // Colors
  colorBackground: colors.background,
  colorPrimary: colors.primary,
  colorPrimaryHover: darken(0.1, colors.primary),
  colorSecondary: colors.secondary,
  colorSecondaryHover: darken(0.1, colors.secondary),
  colorWhite: colors.white,
  colorBlack: colors.black,
  colorBlackHover: darken(0.1, colors.black),
  colorBlackSecondary: rgba(colors.black, 0.5),
  colorAccent: colors.accent,
  colorAccentHover: darken(0.1, colors.accent),
  colorSuccess: colors.success,
  colorSuccessHover: darken(0.1, colors.success),
  colorError: colors.error,
  colorErrorHover: darken(0.1, colors.error),
  colorBorder: lighten(0.1, colors.accent),
  colorBorderInput: rgba(colors.black, 0.15),
  colorBorderInputHover: rgba(colors.black, 0.3),
  colorBorderInputActive: rgba(colors.black, 0.4),
  colorShadow: colors.shadow,
  colorMask: rgba(colors.black, 0.3),
  // Fonts
  fontFamily: "'Open Sans', 'Helvetica Neue', Arial, sans-serif",
  fontFamilyMonospace: 'monospace',
  fontWeightLight: '300',
  fontWeightRegular: '400',
  fontWeightSemibold: '600',
  fontWeightBold: '700',
  fontWeightExtrabold: '800',
  // Font Size
  fontSizeHeadingXxSmall: '.825rem',
  fontSizeHeadingXSmall: '1rem',
  fontSizeHeadingSmall: '1.25rem',
  fontSizeHeadingMedium: '1.5rem',
  fontSizeHeadingLarge: '2.25rem',
  fontSizeHeadingXLarge: '3rem',
  fontSizeHeadingXxLarge: '4.5rem',
  fontSizeHeadingXxxLarge: '10rem',
  fontSizeTextXxSmall: '.5rem',
  fontSizeTextXSmall: '.625rem',
  fontSizeTextSmall: '.75rem',
  fontSizeTextMedium: '.875rem',
  fontSizeTextLarge: '1rem',
  fontSizeTextXLarge: '1.15rem',
  // Line Height
  lineHeightHeading: '1.25',
  lineHeightText: '1.5',
  lineHeightTall: '2.2',
  // Kerning
  letterSpacingNarrow: '-10px',
  letterSpacingWide: '3px',
  // Spacing
  spacingXSmall: '.5rem',
  spacingXxSmall: '.25rem',
  spacingXxxSmall: '.125rem',
  spacingSmall: '.75rem',
  spacingMedium: '1rem',
  spacingLarge: '1.5rem',
  spacingXLarge: '2rem',
  spacingXxLarge: '3rem',
  spacingXxxLarge: '4rem',
  // Borders
  borderWidthThin: '1px',
  borderWidthThick: '2px',
  // Positioning
  positioningCentered: '0 auto',
  // Radius
  borderRadiusCircle: '50%',
  borderRadiusSmall: '2px',
  borderRadiusMedium: '3px',
  borderRadiusLarge: '5px',
  borderRadiusPill: '240px',
  // Shadow
  shadowSubtle: `0 2px 4px 0 ${lighten(0.5, colors.shadow)}`,
  shadowSmall: `0 2px 4px 0 ${colors.shadow}`,
  shadowMedium: `0 4px 8px 0 ${colors.shadow}`,
  shadowLarge: `0 8px 16px 0 ${colors.shadow}`,
  shadowBig: `0 16px 24px 0 ${colors.shadow}`,
  shadowDeep: `0 24px 32px 0 ${colors.shadow}`,
  shadowLeft: `-4px 0 12px 0 ${colors.shadow}`,
  shadowInsertSubtle: `inset 0 1px 2px ${colors.shadow}`,
  // Time
  durationQuickly: '.1s',
  durationImmediately: '.05s',
  durationToastMedium: '9.6s',
  durationSlowly: '.4s',
  durationToastShort: '4.8s',
  durationPaused: '3.2s',
  durationPromptly: '.2s',
  durationSlide: '.25s',
  // Z-index
  zIndexDefault: '1',
  zIndexModal: '8000',
  zIndexSpinner: '9000',
  zIndexToast: '10000',
};

export default tokens;
