name: deploy-preview

# Begin a preview build every time a pull request is opened.
#
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Get Yarn
        run: npm i -g yarn

      - name: Installing
        run: yarn

      - name: Pre Build
        run: yarn prebuild

      - name: Linting
        run: yarn lint:all

      - name: Unit Testing
        run: yarn test:ci:unit

      - name: Build
        run : yarn build:next

      - name: Integration Testing
        run: yarn test:ci:integration
        env:
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          IDENTITY_CLIENT_ID: ${{ secrets.IDENTITY_CLIENT_ID }}
          IDENTITY_CLIENT_SECRET: ${{ secrets.IDENTITY_CLIENT_SECRET }}
          PROVIDER_PORTAL_BASE_URL: ${{ secrets.PROVIDER_PORTAL_BASE_URL }}
          PROVIDER_PORTAL_API_BASIC_AUTH_USERNAME: ${{ secrets.PROVIDER_PORTAL_API_BASIC_AUTH_USERNAME }}
          PROVIDER_PORTAL_API_BASIC_AUTH_PASSWORD: ${{ secrets.PROVIDER_PORTAL_API_BASIC_AUTH_PASSWORD }}
          PROVIDER_PORTAL_API_REFERER: https://patient-dev.genedx.com
          PIMCORE_URL: "https://stage.genedx.com/gdx-webservices/patient"
          PIMCORE_KEY: ${{ secrets.PIMCORE_KEY }}
          NEXT_PUBLIC_PIMCORE_DOMAIN: "https://stage.genedx.com"
          NEXT_PUBLIC_GTM_ID: ${{ secrets.GTM_ID_DEV }}
          CYPRESS_AUTH0_ROOT: ${{ secrets.CYPRESS_AUTH0_ROOT }}
          CYPRESS_AUTH0_GUID_TEST_ORDERED: ${{ secrets.CYPRESS_AUTH0_GUID_TEST_ORDERED }}
          CYPRESS_AUTH0_USERNAME_TEST_ORDERED: ${{ secrets.CYPRESS_AUTH0_USERNAME_TEST_ORDERED }}
          CYPRESS_AUTH0_PASSWORD_TEST_ORDERED: ${{ secrets.CYPRESS_AUTH0_PASSWORD_TEST_ORDERED }}
          CYPRESS_AUTH0_GUID_TEST_IN_LAB: ${{ secrets.CYPRESS_AUTH0_GUID_TEST_IN_LAB }}
          CYPRESS_AUTH0_USERNAME_TEST_IN_LAB: ${{ secrets.CYPRESS_AUTH0_USERNAME_TEST_IN_LAB }}
          CYPRESS_AUTH0_PASSWORD_TEST_IN_LAB: ${{ secrets.CYPRESS_AUTH0_PASSWORD_TEST_IN_LAB }}
          CYPRESS_AUTH0_GUID_RESULTS_READY: ${{ secrets.CYPRESS_AUTH0_GUID_RESULTS_READY }}
          CYPRESS_AUTH0_USERNAME_RESULTS_READY: ${{ secrets.CYPRESS_AUTH0_USERNAME_RESULTS_READY }}
          CYPRESS_AUTH0_PASSWORD_RESULTS_READY: ${{ secrets.CYPRESS_AUTH0_PASSWORD_RESULTS_READY }}
          CYPRESS_AUTH0_GUID_RESULTS_VIEWED: ${{ secrets.CYPRESS_AUTH0_GUID_RESULTS_VIEWED }}
          CYPRESS_AUTH0_USERNAME_RESULTS_VIEWED: ${{ secrets.CYPRESS_AUTH0_USERNAME_RESULTS_VIEWED }}
          CYPRESS_AUTH0_PASSWORD_RESULTS_VIEWED: ${{ secrets.CYPRESS_AUTH0_PASSWORD_RESULTS_VIEWED }}
