name: deploy-container

# Begin a release build every time a push to main occurs.
#
on:
  push:
    branches: [main]

jobs:
  deploy-docker-container:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_HOST }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.ACR_HOST }}/pandas:dev
            ${{ secrets.ACR_HOST }}/pandas:qa
            ${{ secrets.ACR_HOST }}/pandas:prod
            ${{ secrets.ACR_HOST }}/pandas:${{ github.sha }}
            ${{ secrets.ACR_HOST }}/pandas:latest
